chore: added conventional commit hooks. Addresses #5

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -33,15 +33,20 @@ if ! check_requirements; then
   pip3 install -r .husky/requirements.txt
 fi
 
-# checks repo for an issue matching the one referenced in commit message
-python .husky/validate-issue.py --message "$commit_message"
 
 # check conventional commits
-if ! head -1 "$commit_message_file" | grep -qE "^(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert)(\(.+?\))?: .{1,}$"; then
-    echo "Aborting commit. Your commit message is invalid." >&2
+if ! head -1 "$commit_message_file" | grep -q ":"; then
+    echo "Aborting commit. Conventional commit must be followed by a ':'. For example, 'chore: typo #4'" >&2
+    exit 1
+fi
+if ! head -1 "$commit_message_file" | grep -qE "^(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert|BREAKING CHANGE)(\(.+?\))?: .{1,}$"; then
+    echo "Aborting commit with $temp. Must use conventional commit. https://www.conventionalcommits.org/en/v1.0.0/" >&2
     exit 1
 fi
 if ! head -1 "$commit_message_file" | grep -qE "^.{1,88}$"; then
     echo "Aborting commit. Your commit message is too long." >&2
     exit 1
 fi
+
+# checks repo for an issue matching the one referenced in commit message
+python .husky/validate-issue.py --message "$commit_message"
